input_img:
  resized_rome.png
img_size:
  !!python/tuple [4096,4224] #[4096,4177]
step_size:
  128 #For cae method: 128
tile_size:
  !!python/tuple [128,128,3]

final_img_size:
  !!python/tuple [4096,4224]

patch_tile_size:
  !!python/tuple [33,32]

trained_path:
  cae_trained.pth

