num_epochs: 800
batch_size: 16
learning_rate: 0.0001
resume: false
checkpoint: null
start_epoch: 1
exp_name: training_256
patch_size: 256
batch_every: 1
save_every: 400
epoch_every: 400
shuffle: true
dataset_path: /home/alex/workspace/ml-data/cae/datasets/yt_small_720p
num_workers: 16
device: cuda
